spring:
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 300
        min-idle: 100
        max-idle: 100
        max-wait: 10000
time:
  cron: 0 28 9 * * ?