spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
    publisher-confirms: true
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 300
        min-idle: 100
        max-idle: 100
        max-wait: 10000
  datasource:
    url: jdbc:mysql://localhost:3306/yun6?serverTimezone=UTC
    username: root
    password: 802386
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
time:
  cron: 0 28 9 * * ?